// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Town.Tile
{

public enum TileTerrainType : sbyte
{
  Flat = 0,
  Mountain = 1,
  Water = 2,
};


}
